# Generic imports
from fastapi import FastAPI, Depends
from sqlalchemy.orm import Session
#from sqlalchemy.dialects.mssql.information_schema import sequences

# Local imports
from observatory_server.datamodel import (
    Observation,
    ObservationOrm,
    ObservationStatus,
    PKTYPE_MODEL,
)
from observatory_server.db_utils import (
    engine,
    get_session,
    pk_hash
)

# -----------------------------
# FastAPI app
# -----------------------------
app = FastAPI()

################################################################################
# TODELETE
from pydantic import BaseModel, ConfigDict
from typing import List, Optional
from sqlalchemy.orm import DeclarativeBase

class Base(DeclarativeBase):
    pass

# class Item(Base):
#     __tablename__ = "items"
#
#     id = Column(Integer, primary_key=True, index=True)
#     name = Column(String, nullable=False)
#     description = Column(String, nullable=True)

# class ItemModel(BaseModel):
#     name: str
#     description: str | None = None

# Create the database tables
Base.metadata.drop_all(bind=engine)
Base.metadata.create_all(bind=engine)
################################################################################
@app.post("/request_observation")
def create_item(item, db: Session = Depends(get_session)):
    #db_item = Item(name=item.name, description=item.description)
    #db.add(db_item)
    #db.commit()
    #db.refresh(db_item)  # refresh to get autogenerated ID
    # return db_item
    print("Called")
    pass

# Run the server with uvicorn main:app --reload