# Generic imports
from fastapi import FastAPI, Depends
from sqlalchemy.orm import Session
#from sqlalchemy.dialects.mssql.information_schema import sequences
import uvicorn

# Local imports
from observatory_server.datamodel import (
    Base,
    Observation,
    ObservationOrm,
    ObservationStatus,
    PKTYPE_MODEL,
)
from observatory_server.db_utils import (
    engine,
    get_session,
    pk_hash
)

# -----------------------------
# FastAPI app
# -----------------------------
app = FastAPI()

################################################################################
# TODELETE
from pydantic import BaseModel, ConfigDict
from typing import List, Optional, Dict, Any
# from sqlalchemy.orm import DeclarativeBase
#
# class Base(DeclarativeBase):
#     pass


# l = {
#     'target_id': 2,
#     'params': {
#         'cadence_strategy': '',
#         'facility': 'RemoteObservatory',
#         'target_id': 2,
#         'observation_type': 'default_field',
#         'exposure_time': 300,
#         'exposure_count': 43
#     }
# }

# class Item(Base):
#     __tablename__ = "items"
#
#     id = Column(Integer, primary_key=True, index=True)
#     name = Column(String, nullable=False)
#     description = Column(String, nullable=True)

# class ItemModel(BaseModel):
#     name: str
#     description: str | None = None

# Create the database tables
Base.metadata.drop_all(bind=engine)
Base.metadata.create_all(bind=engine)
################################################################################
@app.post("/request_observation")
#def request_observation(observation: dict[Any, Any], db: Session = Depends(get_session)):
def request_observation(observation: Observation, db: Session = Depends(get_session)):
    db_item = ObservationOrm(**observation.model_dump())
    db.add(db_item)
    db.commit()
    db.refresh(db_item)  # refresh to get autogenerated ID
    return db_item.to_dict()
    # print("test")


# Run the server with uvicorn main:app --reload
# OR
if __name__ == "__main__":
    # Create the database tables
    uvicorn.run(app, host="0.0.0.0", port=8888)
