apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb-observatory:8086
    secureJsonData:
      token: observatory
    jsonData:
      version: Flux
      organization: observatory
      defaultBucket: observatory
      tlsSkipVerify: true
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    access: proxy
    url: http://influxdb-observatory:8086
    # This database should be mapped to a bucket
    database: observatory
    jsonData:
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token observatory'