# Doc from https://hub.docker.com/_/eclipse-mosquitto



# Then run the configuration with:
# docker run \
# -p 1883:1883 \
# -p 9001:9001 \
# -d \
# --name mosquitto-remoteobservatory \
# -v $PWD/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro \
# -v /mdata:/mosquitto/data \
# -v /log:/mosquitto/log \
# eclipse-mosquitto


