{
 "title": "Observatory",
 "time": { "from": "2023-01-05T19:34:15.660Z", "to": "2023-01-05T21:16:13.424Z" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "observatory" },
   { "name": "host", "label": "Host", "query": "observatory" },
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "Weather", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rain",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_weather\")\n  |> filter(fn: (r) => r._field == \"WEATHER_RAIN_HOUR\")\n  |> yield(name: \"rain\")"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_weather\")\n  |> filter(fn: (r) => r._field == \"WEATHER_WIND_SPEED\")\n  |> yield(name: \"wind_speed\")"
    }
   ]
  },
  {
   "title": "Safety state",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_weather\")\n  |> filter(fn: (r) => r._field == \"safe\")\n  |> yield(name: \"safe\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_weather\")\n  |> filter(fn: (r) => r._field == \"WEATHER_TEMPERATURE\")\n  |> yield(name: \"temperature\")"
    }
   ]
  },
  {
   "title": "Wind Gust",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_weather\")\n  |> filter(fn: (r) => r._field == \"WEATHER_WIND_GUST\")\n  |> yield(name: \"rain\")"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_weather\")\n  |> filter(fn: (r) => r._field == \"WEATHER_RAIN_HOUR\")\n  |> yield(name: \"wind_speed\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_weather\")\n  |> filter(fn: (r) => r._field == \"WEATHER_TEMPERATURE\")\n  |> yield(name: \"temperature\")"
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_weather\")\n  |> filter(fn: (r) => r._field == \"WEATHER_WIND_SPEED\")\n  |> yield(name: \"wind_speed\")"
    }
   ]
  },
  {
   "title": "Observatory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Observatory Last State",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$bucket$/",
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_status\")\n  |> filter(fn: (r) => r._field == \"state\")\n  |> yield(name: \"state\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Observatory utilization",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\n\nstates_time_serie = from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_status\")\n  |> filter(fn: (r) => r._field == \"state\")\n\nunique_states = states_time_serie\n  |> unique()\n  |> findColumn(fn: (key) => true, column: \"_value\")\n\n// Define a helper function to extract a row as a record\ngetRow = (tables=<-, idx=0) => {\n    extract = tables\n        |> findRecord(fn: (key) => true, idx: idx)\n    return extract\n}\n\nget_state_duration = (x) => {\n  state_duration = states_time_serie\n    // For each input table, elapsed() returns the same table without the first row (because there is no previous time to derive the elapsed time from) and an additional column containing the elapsed time.\n    |> stateDuration(fn: (r) =>\n      r._value == x,\n      column: \"state_duration\",\n      unit: 1s\n      )\n    // We need to sort backward in order to get positive value when doing difference on elapsed time to correspond on the current state\n    //|> sort(columns: [\"_time\"], desc: true)\n    // For each input table with n rows, difference() outputs a table with n - 1 rows.\n    |> difference(columns: [\"state_duration\"], nonNegative: false)\n    |> keep(columns: [\"_time\", \"state_duration\"])\n    |> filter(fn: (r) => r[\"state_duration\"] >= 0)\n    |> sum(column: \"state_duration\")\n    |> set(key: \"state_name\", value: x)\n    |> getRow()\n  return state_duration\n}\n\n// Computer the state duration for each state\nstates_durations = unique_states |> array.map(fn: get_state_duration)\n\n// Output the array of records as a table\narray.from(rows: states_durations)"
    }
   ]
  },
  {
   "title": "State timeline",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_status\")\n  |> filter(fn: (r) => r._field == \"state\")\n  |> yield(name: \"state\")"
    }
   ]
  },
  {
   "title": "Guiding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Guiding State",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_guiding_status\")\n  |> filter(fn: (r) => r._field == \"state\")"
    }
   ]
  },
  {
   "title": "Guiding utilization",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 4, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"array\"\n\nstates_time_serie = from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_guiding_status\")\n  |> filter(fn: (r) => r._field == \"state\")\n\nunique_states = states_time_serie\n  |> unique()\n  |> findColumn(fn: (key) => true, column: \"_value\")\n\n// Define a helper function to extract a row as a record\ngetRow = (tables=<-, idx=0) => {\n    extract = tables\n        |> findRecord(fn: (key) => true, idx: idx)\n    return extract\n}\n\nget_state_duration = (x) => {\n  state_duration = states_time_serie\n    // For each input table, elapsed() returns the same table without the first row (because there is no previous time to derive the elapsed time from) and an additional column containing the elapsed time.\n    |> stateDuration(fn: (r) =>\n      r._value == x,\n      column: \"state_duration\",\n      unit: 1s\n      )\n    // We need to sort backward in order to get positive value when doing difference on elapsed time to correspond on the current state\n    //|> sort(columns: [\"_time\"], desc: true)\n    // For each input table with n rows, difference() outputs a table with n - 1 rows.\n    |> difference(columns: [\"state_duration\"], nonNegative: false)\n    |> keep(columns: [\"_time\", \"state_duration\"])\n    |> filter(fn: (r) => r[\"state_duration\"] >= 0)\n    |> sum(column: \"state_duration\")\n    |> set(key: \"state_name\", value: x)\n    |> getRow()\n  return state_duration\n}\n\n// Computer the state duration for each state\nstates_durations = unique_states |> array.map(fn: get_state_duration)\n\n// Output the array of records as a table\narray.from(rows: states_durations)"
    }
   ]
  },
  {
   "title": "Guiding State",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_guiding_status\")\n  |> filter(fn: (r) => r._field == \"state\")"
    }
   ]
  },
  {
   "title": "Guiding Image metrics",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 53 },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_guiding\")\n  |> filter(fn: (r) => contains(value: r._field, set: [\"HFD\", \"AvgDist\", \"SNR\"]))"
    }
   ]
  },
  {
   "title": "RA/DEC guiding error",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 10, "y": 53 },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_guiding\")\n  |> filter(fn: (r) => contains(value: r._field, set: [\"RADistanceRaw\", \"DECDistanceRaw\"]))"
    }
   ]
  },
  {
   "title": "Observations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last Observation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start:-4w, stop:now())\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_field\")\n  |> filter(fn: (r) => r._field == \"name\")"
    }
   ]
  },
  {
   "title": "Latest GCN Notifications",
   "type": "table",
   "gridPos": { "h": 14, "w": 13, "x": 9, "y": 65 },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start:-1w, stop:now())\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_broker\")\n  |> filter(fn: (r) => r._field == \"data\")"
    }
   ]
  },
  {
   "title": "Observation history",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 70 },
   "targets": [
    {
     "query": "from(bucket: \"$bucket\")\n  |> range(start:-1w, stop:now())\n  |> filter(fn: (r) => r.host == \"$host\")\n  |> filter(fn: (r) => r._measurement == \"mqtt_observatory_field\")\n  |> filter(fn: (r) => r._field == \"name\")"
    }
   ]
  }
 ]
}