@startuml Camera
namespace Camera {
  namespace AbstractCamera {}
  namespace IndiASICamera {}
  namespace IndiAbstractCamera {}
  namespace IndiCamera {}
  namespace IndiASICameraNonCool {}
  namespace IndiAbstractCameraSimulator {}
  namespace IndiEos350DCamera {}
  namespace IndiEos6DCamera {}
  namespace IndiVirtualCamera {}
}
class Camera.AbstractCamera.AbstractCamera {
  _image_dir: None
  serv_time: None
  do_acquisition: None
  do_guiding: None
  do_pointing: None
  do_adjust_pointing: None
  do_autofocus: None
  camera_name: None
  filter_type: None
  _file_extension: None
  _serial_number: None
}
class Camera.IndiASICamera.IndiASICamera {
}
class Camera.IndiAbstractCamera.IndiAbstractCamera {
  indi_camera_config: None
}
class Camera.IndiCamera.IndiCamera {
  pointing_seconds: None
  adjust_center_x: None
  adjust_center_y: None
  adjust_roi_search_size: None
  adjust_pointing_seconds: None
  autofocus_seconds: None
  autofocus_roi_size: None
  autofocus_merit_function: None
  exp_time_sec: None
  gain: None
}
class Camera.IndiASICameraNonCool.IndiASICameraNonCool {
}
class Camera.IndiAbstractCameraSimulator.IndiAbstractCameraSimulator {
}
class Camera.IndiEos350DCamera.IndiEos350DCamera {
}
class Camera.IndiEos6DCamera.IndiEos6DCamera {
}
class Camera.IndiVirtualCamera.IndiVirtualCamera {
}
Camera.IndiAbstractCamera.IndiAbstractCamera <|-- Camera.IndiASICamera.IndiASICamera
Camera.IndiCamera.IndiCamera <|-- Camera.IndiAbstractCamera.IndiAbstractCamera
Camera.AbstractCamera.AbstractCamera <|-- Camera.IndiAbstractCamera.IndiAbstractCamera
Camera.IndiASICamera.IndiASICamera <|-- Camera.IndiASICameraNonCool.IndiASICameraNonCool
Camera.IndiAbstractCamera.IndiAbstractCamera <|-- Camera.IndiAbstractCameraSimulator.IndiAbstractCameraSimulator
Camera.IndiAbstractCamera.IndiAbstractCamera <|-- Camera.IndiEos350DCamera.IndiEos350DCamera
Camera.IndiAbstractCamera.IndiAbstractCamera <|-- Camera.IndiEos6DCamera.IndiEos6DCamera
Camera.IndiCamera.IndiCamera <|-- Camera.IndiVirtualCamera.IndiVirtualCamera
footer Generated by //py2puml//
@enduml
