@startuml helper
namespace helper {
  namespace ArduinoIO {}
  namespace client {}
  namespace IndiClient {}
  namespace IndiDevice {}
  namespace device {}
}
class helper.ArduinoIO.ArduinoIO {
  board: None
  _serial_data: None
  _pub: None
  _sub: None
  _last_reading: None
  _report_next_reading: None
  _cmd_channel: None
  _keep_running: None
}
class helper.client.INDIClient {
  running: None
  client_connecting: None
  reader: None
  writer: None
  to_indiQ: None
  port: None
  host: None
  read_width: None
  communication_over_event: None
}
class helper.IndiClient.IndiClient {
  device_subscriptions: None
  ioloop: None
  thread: None
}
class helper.IndiClient.SingletonIndiClientHolder {
}
class helper.IndiDevice.IndiDevice {
  indi_client: None
  is_client_connected: None
  indi_client_config: None
  timeout: None
  interfaces: None
  debug: None
}
class helper.IndiDevice.PyIndi {
}
class helper.device.VectorHandler {
  devicename: None
  vectorname: None
  callback: None
}
class helper.device.device {
  device_name: None
  _factory: None
  expat: None
  current_vector: None
  current_element: None
  current_xml_str: None
  blob_event: None
  blob_queue: None
  custom_element_handler_dict: None
  custom_vector_handler_dict: None
  blob_def_handler: None
  number_def_handler: None
  switch_def_handler: None
  text_def_handler: None
  light_def_handler: None
  message_handler: None
  timeout_handler: None
  property_vectors: None
  property_vectors_lock: None
  timer_queue: None
}
class helper.device._indinameconventions {
  basenames: None
}
class helper.device._indiobjectfactory {
  tagfactory: None
  elementclasses: None
  vectorclasses: None
}
class helper.device._inditagfactory {
  dict: None
}
class helper.device.indiblob {
  format: None
}
class helper.device.indiblobvector {
}
class helper.device.indielement {
  _old_value: None
}
class helper.device.indilight {
  _value: None
}
class helper.device.indilightvector {
  tag: None
}
class helper.device.indimessage {
  device: None
  timestamp: None
  _value: None
}
class helper.device.indinamedobject {
  name: None
  label: None
  label: None
}
class helper.device.indinumber {
  _value: None
  format: None
  _min: None
  _max: None
  _step: None
}
class helper.device.indinumbervector {
}
class helper.device.indiobject {
  tag: None
}
class helper.device.indipermissions {
  perm: None
}
class helper.device.indiswitch {
}
class helper.device.indiswitchvector {
  rule: None
}
class helper.device.inditext {
}
class helper.device.inditextvector {
}
class helper.device.inditransfertype {
}
class helper.device.inditransfertypes {
}
class helper.device.indivector {
  device: None
  timestamp: None
  timeout: None
  _light: None
  group: None
  _perm: None
  _message: None
  _message: None
  elements: None
  port: None
  host: None
}
class helper.device.indixmltag {
  _is_vector: None
  _is_element: None
  _is_message: None
  _transfertype: None
  _index: None
  _basename: None
  _initial_tag: None
  _initial_tag: None
}
helper.IndiClient.SingletonIndiClientHolder <|-- helper.IndiClient.IndiClient
helper.client.INDIClient <|-- helper.IndiClient.IndiClient
helper.device.device <|-- helper.IndiDevice.IndiDevice
helper.device._indinameconventions <|-- helper.device._indiobjectfactory
helper.device._indinameconventions <|-- helper.device._inditagfactory
helper.device.indielement <|-- helper.device.indiblob
helper.device.indivector <|-- helper.device.indiblobvector
helper.device.indinamedobject <|-- helper.device.indielement
helper.device.indielement <|-- helper.device.indilight
helper.device.indivector <|-- helper.device.indilightvector
helper.device.indiobject <|-- helper.device.indimessage
helper.device.indiobject <|-- helper.device.indinamedobject
helper.device.indielement <|-- helper.device.indinumber
helper.device.indivector <|-- helper.device.indinumbervector
helper.device.indielement <|-- helper.device.indiswitch
helper.device.indivector <|-- helper.device.indiswitchvector
helper.device.indielement <|-- helper.device.inditext
helper.device.indivector <|-- helper.device.inditextvector
helper.device.inditransfertype <|-- helper.device.inditransfertypes
helper.device.indinamedobject <|-- helper.device.indivector
helper.device._indinameconventions <|-- helper.device.indixmltag
footer Generated by //py2puml//
@enduml

